#ifndef REMOTE_CHRISMAS_TREE_LEDS_CONSTANTS_H
#define REMOTE_CHRISMAS_TREE_LEDS_CONSTANTS_H

constexpr size_t EEPROM_SIZE = 128;
constexpr byte MAX_SSID_LENGTH = 32;
constexpr byte MAX_WIFI_PASSWORD_LENGTH = 63;

#endif //REMOTE_CHRISMAS_TREE_LEDS_CONSTANTS_H
