#ifndef REMOTE_CHRISTMAS_TREE_LED_CONSTANTS_H
#define REMOTE_CHRISTMAS_TREE_LED_CONSTANTS_H

constexpr size_t EEPROM_SIZE = 128;
constexpr byte MAX_SSID_LENGTH = 32;
constexpr byte MAX_WIFI_PASSWORD_LENGTH = 63;

#endif //REMOTE_CHRISTMAS_TREE_LED_CONSTANTS_H
